/*
 * Approvals API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.approvals.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.approvals.model.DecisionMode;
import com.smartrecruiters.api.approvals.model.Step;
import com.smartrecruiters.api.approvals.model.Subject;
import com.smartrecruiters.api.approvals.model.Type;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Approval request
 */
@ApiModel(description = "Approval request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-30T17:54:28.520346+01:00[Europe/Rome]")
public class ApprovalRequest {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private Subject subject;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Type type;

  public static final String SERIALIZED_NAME_DECISION_MODE = "decisionMode";
  @SerializedName(SERIALIZED_NAME_DECISION_MODE)
  private DecisionMode decisionMode;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<Step> steps = null;


  public ApprovalRequest id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Approval request id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Approval request id")

  public String getId() {
    return id;
  }



  public void setId(String id) {
    this.id = id;
  }


  public ApprovalRequest subject(Subject subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Subject getSubject() {
    return subject;
  }



  public void setSubject(Subject subject) {
    this.subject = subject;
  }


  public ApprovalRequest type(Type type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type getType() {
    return type;
  }



  public void setType(Type type) {
    this.type = type;
  }


  public ApprovalRequest decisionMode(DecisionMode decisionMode) {
    
    this.decisionMode = decisionMode;
    return this;
  }

   /**
   * Get decisionMode
   * @return decisionMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DecisionMode getDecisionMode() {
    return decisionMode;
  }



  public void setDecisionMode(DecisionMode decisionMode) {
    this.decisionMode = decisionMode;
  }


  public ApprovalRequest steps(List<Step> steps) {
    
    this.steps = steps;
    return this;
  }

  public ApprovalRequest addStepsItem(Step stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<Step>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Step> getSteps() {
    return steps;
  }



  public void setSteps(List<Step> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApprovalRequest approvalRequest = (ApprovalRequest) o;
    return Objects.equals(this.id, approvalRequest.id) &&
        Objects.equals(this.subject, approvalRequest.subject) &&
        Objects.equals(this.type, approvalRequest.type) &&
        Objects.equals(this.decisionMode, approvalRequest.decisionMode) &&
        Objects.equals(this.steps, approvalRequest.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subject, type, decisionMode, steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApprovalRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    decisionMode: ").append(toIndentedString(decisionMode)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

