/*
 * Approvals API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.smartrecruiters.api.approvals.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.smartrecruiters.api.approvals.model.Approver;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Required steps to complete approval
 */
@ApiModel(description = "Required steps to complete approval")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-30T17:54:28.520346+01:00[Europe/Rome]")
public class Step {
  public static final String SERIALIZED_NAME_APPROVERS = "approvers";
  @SerializedName(SERIALIZED_NAME_APPROVERS)
  private List<Approver> approvers = null;


  public Step approvers(List<Approver> approvers) {
    
    this.approvers = approvers;
    return this;
  }

  public Step addApproversItem(Approver approversItem) {
    if (this.approvers == null) {
      this.approvers = new ArrayList<Approver>();
    }
    this.approvers.add(approversItem);
    return this;
  }

   /**
   * The order matters when type is &#x60;sequential&#x60;
   * @return approvers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order matters when type is `sequential`")

  public List<Approver> getApprovers() {
    return approvers;
  }



  public void setApprovers(List<Approver> approvers) {
    this.approvers = approvers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Step step = (Step) o;
    return Objects.equals(this.approvers, step.approvers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Step {\n");
    sb.append("    approvers: ").append(toIndentedString(approvers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

